# -*- coding: utf-8 -*-
"""Day1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192FJrUWwvq33ujmSsXLwSNA403hW-m3d
"""

# Variables
name = "John"
age = 18
marks = 95.5
is_student = True

print(name)
print(age)
print(marks)
print(is_student)

# Python Program to Print Student Marks Using a Loop

# List of marks
marks = [85, 90, 78, 92, 88]

# Display the marks
print("Student Marks:")

# Loop through the list
for m in marks:
    print(m)


# Function to add two numbers

def add(a, b):
    return a + b

result = add(10, 20)
print("Sum =", result)

# Hello World
print("Hello World")

# add two numbers
a=20
b=30
print(a+b)
print(a-b)
print(a*b)
print(a/b)

# Ever or odd
num=int(input("Enter a number: "))
if num%8==0:
    print("Even")
else:
    print("Odd")

# Largest of two numbers
a=int(input('First: '))
b=int(input('Second: '))
if a>b:
    print(a)
else:
    print(b)

# Multiplication table
num=int(input('Enter a number:'))
for i in range(1,11):
  print(num,'x',i,'=',num*i)

# Sum of First N Numbers
n=int(input('Enter n:'))
s=0
for i in range(1,n+1):
  s+=i
  print(s)

# Factorial
num=int(input('Enter a number:'))
f=1
for i in range(1,num+1):
  f*=i
  print(f)

# Fibonacci Series
n=int(input('Enter terms:'))
a,b=0,1
for i in range(n):
  print(a,end='')
  a,b=b,a+b

# Reverse a Number
num=int(input('Enter number: '))
rev=0
while num>0:
    d=num%10
    rev=rev*10+d
    num//=10
print(rev)

# Prime Number
num=int(input('Enter number: '))
count=0
for i in range(1,num+1):
    if num%i==0:
        count+=1
print('Prime' if count==2 else 'Not Prime')

# Palindrome Number
num=int(input('Enter number:'))
t=num
rev=0
while t>0:
  d=t%10
  rev=rev*10+d
  t//=10
  print('Palindrome' if num==rev else 'Not Palindrome')

# Swap Two Numbers
a=10
b=20
print('Before',a,b)
a,b=b,a
print('After',a,b)

# Count Vowels
text=input('Enter text: ')
count=0
for ch in text.lower():
    if ch in 'aeiou':
        count+=1
print(count)

# Maximum in a List
nums=[10,45,23,89,12]
print(max(nums))

# Minimum in a List
nums=[10,45,23,89,12]
print(min(nums))

# Count Even and Odd
nums=[10,15,22,31,48]
e=o=0
for n in nums:
    if n%2==0:
        e+=1
    else:
        o+=1
print(e,o)

# Sum and Average
nums=[10,20,30,40,50]
print(sum(nums))
print(sum(nums)/len(nums))

# Armstrong Number
num=int(input('Enter number: '))
p=len(str(num))
s=0
t=num
while t>0:
 d=t%10
 s+=d**p
 t//=10
print('Armstrong' if s==num else 'Not Armstrong')

# Star Pattern
for i in range(1,6):
    print('*'*i)

# Square Function
def square(n):
    return n*n
print(square(5))