# -*- coding: utf-8 -*-
"""Day2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDzjI2Vqi3-toXcl2t_fAOIBvcZ63sJY
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv("Iris.csv")

print("=" * 60)
print("FIRST FIVE RECORDS")
print("=" * 60)
print(df.head())

print("\nDATASET INFORMATION")
df.info()

print("\nDATASET SHAPE")
print(df.shape)

rows, cols = df.shape

print("\nCOLUMN NAMES")
print(df.columns)

print("\nSTATISTICAL SUMMARY")
print(df.describe())

print("\nMISSING VALUES")
print(df.isnull().sum())

print("\nDUPLICATE VALUES")
print(df.duplicated().sum())

print("\nUNIQUE SPECIES")
print(df["Species"].unique())

print("\nCLASS COUNT")
print(df["Species"].value_counts())

print("\nLAST FIVE RECORDS")
print(df.tail())