# -*- coding: utf-8 -*-
"""Day3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d0VBrQAQseviay6XuK-95OZ52IH2JyLj
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv("Titanic-Dataset.csv")

print("=" * 50)
print("First Five Rows")
print(df.head())

print("=" * 50)
print("Dataset Information")
print(df.info())

print("=" * 50)
print("Missing Values")
print(df.isnull().sum())

print(df.describe())

df.drop_duplicates(inplace=True)

df["Age"].fillna(df["Age"].mean(), inplace=True)

df.isnull().sum()

if "Age" in df.columns:
    df["Age"] = df["Age"].fillna(df["Age"].mean())

df.isnull().sum()

if "Cabin" in df.columns:
    df.drop("Cabin", axis=1, inplace=True)

df.isnull().sum()

df.drop("SibSp",axis=1)

df.drop("PassengerId",axis=1)

df.duplicated().sum()