# -*- coding: utf-8 -*-
"""Day4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WxovsIca6UPUMQBUNocWzStkPXwVOP6k
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

print("="*60)
print("Libraries Imported Successfully")
print("="*60)

from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing(as_frame=True)

df = housing.frame

print(df.head())

print("Dataset Info")
print("=" * 50)
print(df.info())

print("=" * 50)
print("Statistical Summary")
print("=" * 50)
print(df.describe())

print("=" * 50)
print("Missing Values")
print("=" * 50)
print(df.isnull().sum())

X = df.drop("MedHouseVal", axis=1)
y = df["MedHouseVal"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining Shape:", X_train.shape)
print("Testing Shape :", X_test.shape)

model = LinearRegression()

model.fit(X_train, y_train)

print("\nModel Training Completed")

y_pred = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print(comparison.head())

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("\nEvaluation Metrics")
print("-" * 40)
print("MAE :", mae)
print("MSE :", mse)
print("RMSE :", rmse)
print("R2 Score :", r2)

coef = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print("\nFeature Importance")
print(coef)

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual House Price")

plt.ylabel("Predicted House Price")

plt.title("Actual vs Predicted")

plt.grid(True)

plt.show()

residuals = y_test - y_pred

plt.figure(figsize=(8,6))

plt.scatter(y_pred, residuals)

plt.axhline(y=0,color='red')

plt.xlabel("Predicted")

plt.ylabel("Residual")

plt.title("Residual Plot")

plt.grid(True)

plt.show()

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np

df = pd.read_excel("Global_Superstore (2).xlsx")

print(df.head())

print(df.info())

print(df.isnull().sum())

print(df.describe())

df.drop_duplicates(inplace=True)

df.isnull().sum()

if "Age" in df.columns:
    df["Age"] = df["Age"].fillna(df["Age"].mean())

df.isnull().sum()

if "Cabin" in df.columns:
    df.drop("Cabin", axis=1, inplace=True)

df.isnull().sum()

df.drop("Ship Date",axis=1)

df.duplicated().sum()

print(df.columns)

print(df.tail)

X = df[["Sales", "Quantity", "Discount"]]

print("\nFeatures")
print(X.head())

y = df["Profit"]

print("\nTarget Variable")
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("\nTraining Data Shape")
print(X_train.shape)

print("\nTesting Data Shape")
print(X_test.shape)

model = LinearRegression()
print("\nLinear Regression Model Created")

model.fit(X_train, y_train)

print("\nModel Training Completed")

model.fit(X_train, y_train)
print("\nIntercept")
print(model.intercept_)
print("\nCoefficints")
coefficients = pd.DataFrame({
  "Feature": X.columns,
    "Coefficient": model.coef_
})
print(coefficients)

model.fit(X_train, y_train)
prediction = model.predict(X_test)

print("\nPrediction Completed")

comparison = pd.DataFrame({
    "Actual Profit":
    y_test.values,
    "Predicted Profi":
    prediction
    })

print("\nActual vs Predicted")
print(comparison.head(20))

mae = mean_absolute_error(y_test, prediction)
mse = mean_squared_error(y_test, prediction)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, prediction)

print("\nMODEL PERFORMANCE")
print("-"*40)

print("Mean Absolute Error :", mae)

print("Mean Squared Error :", mse)

print("Root Mean Squared Error :", rmse)

print("R2 Score :", r2)

new_order = [[500,5,0.10]]
predicted_profit = model.predict(new_order)
print("\nPredicted Profit for New Order")
print(predicted_profit)

plt.figure(figsize=(8,6))
plt.scatter(y_test,prediction)
plt.xlabel("Actual Profit")

plt.ylabel("Predicted Profit")

plt.title("Actual Profit vs Predicted Profit")

plt.grid(True)

plt.show()

residual = y_test-prediction
plt.figure(figsize=(8,6))
plt.scatter(
    prediction,
    residual
)
plt.axhline(
    y=0,
    color='red',
    linestyle='--'
)
plt.xlabel("Predicted Profit")
plt.ylabel("Residul")
plt.title("Residual Plot")
plt.grid(True)
plt.show()

plt.figure(figsize=(6,4))
plt.bar(
    coefficients["Feature"],
   coefficients["Coefficient"]
)
plt.title("Feature Importance")
plt.xlabel("Features")
plt.ylabel("Coefficients")
plt.show()

print("\n")
print("="*60)
print("SUMMARY")
print("="*60)

print("Machine Learning Workflow Completed Successfully.")