# -*- coding: utf-8 -*-
"""Day6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_z_IzANoz23sb-wKPePz4s7JwMogpEQn
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
)
confusion_matrix,
ConfusionMatrixDisplay
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
)

df=pd . read_csv("customer_churn_dataset-training-master (1).csv")

print("="*60)
print("FIRST FIVE RECORDS")
print("="*60)
print(df.head())

print("\n")
print("="*60)
print("DATASET INFORMATION")
print("="*60)

print(df.info())

print("\n")
print("="*60)
print("STATISTICAL SUMMARY")
print("="*60)

print(df.describe())

print("\n")
print("="*60)
print("MISSING VALUES")
print("="*60)

print(df.isnull().sum())

df["Churn"]=df["Churn"].fillna(df["Churn"].mode()[0])

df[""]=df["Churn"].fillna(df["Churn"].mode()[0])

df.isnull().sum()

print("\n")
print("="*60)
print("DUPLICATES")
print("="*60)

print(df.duplicated().sum())

print("\n")
print("="*60)
print("TARGET CLASSES")
print("="*60)

print(df["Gender"].value_counts())

df.dropna(inplace=True)

categorical_cols = ["Gender", "Subscription Type", "Contract Length"]
for col in categorical_cols:
    encoder = LabelEncoder()
    df[col] = encoder.fit_transform(df[col])

X = df.drop("Churn", axis=1)
y = df["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples :", len(X_train))
print("Testing Samples :", len(X_test))

model = LogisticRegression(max_iter=500)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("\n")
print("="*60)
print("MODEL ACCURACY")
print("="*60)

print(f"Accuracy : {accuracy*100:.2f}%")

print("\n")
print("="*60)
print("CLASSIFICATION REPORT")
print("="*60)

print(classification_report(
    y_test,
    y_pred,
    target_names=['Not Churn', 'Churn']
))

cm = confusion_matrix(y_test, y_pred)

print("\n")
print("="*60)
print("CONFUSION MATRIX")
print("="*60)

print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=['Not Churn', 'Churn']
)

disp.plot(cmap="Blues")

plt.title("Confusion Matrix")

plt.show()

importance = np.mean(np.abs(model.coef_), axis=0)

feature_names = X.columns

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importance
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print("\n")
print("="*60)
print("FEATURE IMPORTANCE")
print("="*60)

print(importance_df)

plt.figure(figsize=(8,5))

plt.bar(
    importance_df["Feature"],
    importance_df["Importance"]
)

plt.title("Feature Importance")

plt.xlabel("Features")

plt.ylabel("Importance")

plt.xticks(rotation=20)

plt.show()

print("\n")
print("="*60)
print("NEW CUSTOMER CHURN PREDICTION")
print("="*60)


new_customer_data = {
    'CustomerID': [500000.0],
    'Age': [35.0],
    'Gender': [0.0],
    'Tenure': [24.0],
    'Usage Frequency': [15.0],
    'Support Calls': [2.0],
    'Payment Delay': [10.0],
    'Subscription Type': [1.0],
    'Contract Length': [0.0],
    'Total Spend': [700.0],
    'Last Interaction': [10.0],
    '': [1.0]
}

new_customer_df = pd.DataFrame(new_customer_data)


prediction = model.predict(new_customer_df)


if prediction[0] == 1.0:
    churn_status = "Churn"
else:
    churn_status = "Not Churn"

print("Predicted Churn Status for New Customer :", churn_status)

print("\n")
print("="*60)
print("MULTIPLE CUSTOMER CHURN PREDICTIONS")
print("="*60)

multiple_new_customer_data = [

    {'CustomerID': 500001.0, 'Age': 40.0, 'Gender': 1.0, 'Tenure': 12.0, 'Usage Frequency': 25.0,
     'Support Calls': 8.0, 'Payment Delay': 25.0, 'Subscription Type': 0.0, 'Contract Length': 0.0,
     'Total Spend': 300.0, 'Last Interaction': 5.0, '': 1.0},

    {'CustomerID': 500002.0, 'Age': 28.0, 'Gender': 0.0, 'Tenure': 48.0, 'Usage Frequency': 10.0,
     'Support Calls': 1.0, 'Payment Delay': 2.0, 'Subscription Type': 2.0, 'Contract Length': 2.0,
     'Total Spend': 950.0, 'Last Interaction': 28.0, '': 0.0},

    {'CustomerID': 500003.0, 'Age': 55.0, 'Gender': 1.0, 'Tenure': 30.0, 'Usage Frequency': 18.0,
     'Support Calls': 3.0, 'Payment Delay': 15.0, 'Subscription Type': 1.0, 'Contract Length': 1.0,
     'Total Spend': 600.0, 'Last Interaction': 15.0, '': 1.0}
]


multiple_new_customer_df = pd.DataFrame(multiple_new_customer_data)


predictions = model.predict(multiple_new_customer_df)

print("Multiple Customer Churn Predictions:")
for i, prediction_value in enumerate(predictions):
    if prediction_value == 1.0:
        churn_status = "Churn"
    else:
        churn_status = "Not Churn"
    print(f"Customer {i+1} (ID: {multiple_new_customer_data[i]['CustomerID']}) --> {churn_status}")

import joblib

joblib.dump(model, "iris_model.pkl")

joblib.dump(encoder, "label_encoder.pkl")

print("\nModel Saved Successfully.")

loaded_model = joblib.load("iris_model.pkl")


new_customer_sample_data = {
    'CustomerID': [500004.0],
    'Age': [45.0],
    'Gender': [0.0],
    'Tenure': [36.0],
    'Usage Frequency': [20.0],
    'Support Calls': [3.0],
    'Payment Delay': [15.0],
    'Subscription Type': [1.0],
    'Contract Length': [0.0],
    'Total Spend': [800.0],
    'Last Interaction': [12.0],
    '': [0.0]
}


sample_df = pd.DataFrame(new_customer_sample_data)

pred = loaded_model.predict(sample_df)

print("\nPrediction Using Saved Model")


if pred[0] == 1.0:
    churn_status = "Churn"
else:
    churn_status = "Not Churn"

print("Predicted Churn Status :", churn_status)