# -*- coding: utf-8 -*-
"""Day8 workshop(regression)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1btx9e7czXvjjOoRRxQtqrUUritzrPII5
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

print("="*60)
print("Libraries Imported Successfully")
print("="*60)

df = pd.read_csv("fifa_world_cup_2026_player_performance.csv")

print("\nDataset Loaded Successfully")

print("\nFirst Five Rows")
print(df.head())

print("\nDataset Information")
print(df.info())

print("\nShape of Dataset")
print(df.shape)

print("\nColumn Names")
print(df.columns)

print("\nMissing Values")
print(df.isnull().sum())

df = df.dropna()

print("\nStatistical Summary")
print(df.describe())

X = df[["total_goals_tournament", "total_assists_tournament", "total_minutes_tournament"]]

print("\nFeatures")
print(X.head())

y = df["tournament_rating"]

print("\nTarget Variable")
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("\nTraining Data Shape")
print(X_train.shape)

print("\nTesting Data Shape")
print(X_test.shape)

model = LinearRegression()

print("\nLinear Regression Model Created")

model.fit(X_train, y_train)

print("\nModel Training Completed")

print("\nIntercept")
print(model.intercept_)

print("\nCoefficients")

coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print(coefficients)

prediction = model.predict(X_test)

print("\nPrediction Completed")

comparison = pd.DataFrame({
    "Actual Profit": y_test.values,
    "Predicted Profit": prediction
})

print("\nActual vs Predicted")
print(comparison.head(20))

mae = mean_absolute_error(y_test, prediction)
mse = mean_squared_error(y_test, prediction)
rmse = np.sqrt(mse)



r2 = r2_score(y_test, prediction)

print("\nMODEL PERFORMANCE")
print("-"*40)

print("Mean Absolute Error :", mae)

print("Mean Squared Error :", mse)

print("Root Mean Squared Error :", rmse)

print("R2 Score :", r2)

import pandas as pd

new_order = [[500, 5, 0.10]]

new_order_df = pd.DataFrame(new_order, columns=X.columns)


predicted_profit = model.predict(new_order_df)

print("\nPredicted Tournament Rating for New Order")

print(predicted_profit)

plt.figure(figsize=(8,6))

plt.scatter(
    y_test,
    prediction
)

plt.xlabel("Actual Profit")

plt.ylabel("Predicted Profit")

plt.title("Actual Profit vs Predicted Profit")

plt.grid(True)

plt.show()

residual = y_test - prediction

plt.figure(figsize=(8,6))

plt.scatter(
    prediction,
    residual
)

plt.axhline(
    y=0,
    color='red',
    linestyle='--'
)

plt.xlabel("Predicted Profit")

plt.ylabel("Residual")

plt.title("Residual Plot")

plt.grid(True)

plt.show()

plt.figure(figsize=(6,4))

plt.bar(
    coefficients["Feature"],
    coefficients["Coefficient"]
)

plt.title("Feature Importance")

plt.xlabel("Features")

plt.ylabel("Coefficient")

plt.show()

print("\n")
print("="*60)
print("SUMMARY")
print("="*60)

print("""
1. Dataset Loaded Successfully

2. Selected Features:
      Sales
      Quantity
      Discount

3. Target Variable:
      Profit

4. Dataset Split:
      80% Training
      20% Testing

5. Linear Regression Model Trained

6. Predictions Generated

7. Model Evaluated using:
      MAE
      MSE
      RMSE
      R2 Score

8. Predicted Profit for New Orders

9. Visualized Model Performance

Machine Learning Workflow Completed Successfully.
""")