# -*- coding: utf-8 -*-
"""Day8 workshop(classification)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hn6MqGhVsv7tFjgfZKslZW6wPrqK1FU6
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

df = pd.read_csv("fifa_world_cup_2026_player_performance.csv")

print("="*60)
print("FIRST FIVE RECORDS")
print("="*60)

print(df.head())

print("\n")
print("="*60)
print("DATASET INFORMATION")
print("="*60)

print(df.info())

print("\n")
print("="*60)
print("STATISTICAL SUMMARY")
print("="*60)

print(df.describe())

print("\n")
print("="*60)
print("MISSING VALUES")
print("="*60)

print(df.isnull().sum())

print("\n")
print("="*60)
print("DUPLICATES")
print("="*60)

print(df.duplicated().sum())

if "team" in df.columns:
  df = df.drop("team", axis=1)

print("\n")
print("="*60)
print("TARGET CLASSES")
print("="*60)

print(df["position"].value_counts())

encoder = LabelEncoder()

df["position"] = encoder.fit_transform(df["position"])

print("\nEncoded Classes")

for i, name in enumerate(encoder.classes_):
    print(i, "=", name)

X = df.drop([
    "position", "player_id",
], axis=1)

y = df["position"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples :", len(X_train))
print("Testing Samples :", len(X_test))

model = LogisticRegression(max_iter=500)

X_train_numeric = X_train.select_dtypes(include=np.number)

model.fit(X_train_numeric, y_train)

X_test_numeric = X_test.select_dtypes(include=np.number)
y_pred = model.predict(X_test_numeric)

accuracy = accuracy_score(y_test, y_pred)

print("\n")
print("="*60)
print("MODEL ACCURACY")
print("="*60)

print(f"Accuracy : {accuracy*100:.2f}%")

print("\n")
print("="*60)
print("CLASSIFICATION REPORT")
print("="*60)

print(classification_report(
    y_test,
    y_pred,
    target_names=[str(c) for c in encoder.classes_]
))

cm = confusion_matrix(y_test, y_pred)

print("\n")
print("="*60)
print("CONFUSION MATRIX")
print("="*60)

print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=encoder.classes_
)

disp.plot(cmap="Blues")

plt.title("Confusion Matrix")

plt.show()

importance = np.mean(np.abs(model.coef_), axis=0)

feature_names = X_train_numeric.columns

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importance
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)
print("\n")
print("="*60)
print("FEATURE IMPORTANCE")
print("="*60)

print(importance_df)

plt.figure(figsize=(8,5))

plt.bar(
    importance_df["Feature"],
    importance_df["Importance"]
)

plt.title("Feature Importance")

plt.xlabel("Features")

plt.ylabel("Importance")

plt.xticks(rotation=20)

plt.show()

print("\n")
print("="*60)
print("NEW PLAYER POSITION PREDICTION")
print("="*60)
player_position = encoder.inverse_transform(y_pred)

print("Predicted Player Position :", player_position[0])

species = encoder.inverse_transform(y_pred)
print("\nMultiple Player Position Predictions")
for i, player_specie in enumerate(species):
    print(f"Player {i+1} --> {player_specie}")

import joblib

joblib.dump(model, "iris_model.pkl")

joblib.dump(encoder, "label_encoder.pkl")

print("\nModel Saved Successfully.")

loaded_model = joblib.load("iris_model.pkl")

loaded_encoder = joblib.load("label_encoder.pkl")

species = loaded_encoder.inverse_transform(y_pred)

print("\nPrediction Using Saved Model (Player Position)")

print("Predicted Player Position :", species[0])