# -*- coding: utf-8 -*-
"""Day9.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QqT1tuLgFJoCxC6QUF7ykBsnYdSodR74
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

print("="*60)
print("STEP 1 : Loading Dataset")
print("="*60)

df = pd.read_csv("insurance.csv")

print(df.head())
print("\nShape:", df.shape)

df.isnull().sum()

if "user_id" in df.columns:
    df = df.drop(columns=["user_id"])

print("\nConverting categorical columns...")

categorical_cols = df.select_dtypes(include=["object"]).columns

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

print("Dataset Shape After Encoding:", df.shape)

print("\nPreparing features...")

X = df.copy()



print("Scaling data...")

categorical_cols = X.select_dtypes(include=["object"]).columns
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("\nFinding optimal K...")

wcss = []

for k in range(1,11):
    model = KMeans(n_clusters=k,
                   random_state=42,
                   n_init=10)

    model.fit(X_scaled)
    wcss.append(model.inertia_)

plt.figure(figsize=(8,5))
plt.plot(range(1,11),wcss,marker="o")
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.grid(True)
plt.show()

print(""" Choose the point where the graph bends. That value is usually the optimal number of clusters. For this example we use K = 3. """)

k = 3

kmeans = KMeans(
    n_clusters=k,
    random_state=42,
    n_init=10
)

clusters = kmeans.fit_predict(X_scaled)

df["Cluster"] = clusters

print("\nCluster Counts")
print(df["Cluster"].value_counts())

score = silhouette_score(X_scaled, clusters)

print("\nSilhouette Score =", round(score,3))

if score > 0.7:
    print("Excellent clustering")
elif score > 0.5:
    print("Good clustering")
elif score > 0.3:
    print("Average clustering")
else:
    print("Poor clustering")

print("\nReducing dimensions using PCA...")

pca = PCA(n_components=2)

reduced = pca.fit_transform(X_scaled)

plt.figure(figsize=(8,6))

plt.scatter(
    reduced[:,0],
    reduced[:,1],
    c=clusters
)

plt.title("K-Means Clustering")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()